[book]
authors		= [ "QuineDot" ]
title		= "Learning Rust"
description	= "Advice for learning Rust"
language	= "en"
src		= "src"

[rust]
edition = "2024"

[output.html]
git-repository-url = "https://github.com/QuineDot/rust-learning"
default-theme = "navy"
site-url = "/rust-learning/"
fold.enable = true
